# Generated by Django 5.1 on 2024-10-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastereduxUserActivity',
            fields=[
                ('user_act_id', models.AutoField(db_column='UserAct_ID', primary_key=True, serialize=False)),
                ('waste_category', models.CharField(choices=[('Plastic', 'Plastic'), ('Metal', 'Metal'), ('Glass', 'Glass')], db_column='Waste_Category', max_length=10)),
                ('waste_name', models.CharField(blank=True, db_column='Waste_Name', max_length=135, null=True)),
                ('waste_action', models.CharField(choices=[('Scanned', 'Scanned'), ('Registered', 'Registered')], db_column='Waste_Action', max_length=10)),
                ('waste_location', models.CharField(db_column='Waste_Location', max_length=135)),
                ('activity_date', models.DateField(db_column='ActivityDate')),
                ('is_archived', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], db_column='IsArchived', default='n', max_length=1)),
                ('image_url', models.CharField(db_column='Image_Url', max_length=512)),
            ],
            options={
                'db_table': 'wasteredux_user_activity',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
