# Generated by Django 5.1 on 2024-11-08 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_scannedimage_unrecognizedimages_users_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WastereduxUserActivity',
        ),
        migrations.DeleteModel(
            name='WastereduxUsers',
        ),
    ]
